
## Lunes, 6 de julio

### Plan

Capítulo 1 ¿Qué estudias?  

- Funciones: Descripción de personas
	- 1.4.4 Gramática en contexto: Present tense of regular -er and -ir verbs 
- Actividad e-Portafolio: Mis metas

### Detalles

- hablar de office hours tb 
- la concordancia (articulo, sustantivo, pronombre, verbo)
- present tense verbs
- Metas para clase
	- breakout rooms, discutir metas con los compañeros
- estrategias para la comunicación oral (del viernes, si no hay tiempo, para el martes)
	- las vocales
	- palabras largas

### Tarea

- hoja de metas (3 metas, lista, frases cortas)

### Comentarios








## Martes, 7 de julio

### Plan

Capítulo 2 ¿Quiénes son tus amigos?  

- Funciones: Descripción de personas
	- 2.1.1 Vocabulario en contexto: Mis amigos y yo
- Preparación actividad e-Portafolio - Mi compañero (1:30)
- Entregar para e-Portafolio: Mis metas
- Estrategias para la comunicación oral 

### Detalles

- compartir algunas metas
- más descripción de las personas
- hablar de la primera presentación
	- escoger pareja (poll)
	- como hacer una entrevista
	- tiempo para conseguir información
- estrategias para la comunicación oral
	- las vocales
	- palabras largas

### Tarea

- Nada

### Comentarios

- Las actividades han funcionado bien
- De nuevo no ha habido tiempo para las vocales/palabras largas






## Miércoles, 8 de julio

### Reunión de nivel

- reunión general
- hablar de mesa redonda
- horario para las reuniones (volvemos al horario "normal", 12:30)








## Jueves, 8 de julio

### Plan

Capítulo 2 ¿Quiénes son tus amigos?  

- Funciones: Hablar de su rutina
	- 2.4.1 Gramática en contexto: Adjectives
- Preparación actividad e-Portafolio: Mi compañero (1:30)

### Detalles

- repasar verbos regulares
- relación sujeto verbo
- adjetivos (pizarra interactiva)
- tiempo para practicar presentaciones, conseguir información
- estrategias para la comunicación oral
	- las vocales
	- palabras largas

### Tarea

- ensayar para la presentación oral 

### Comentarios







## Viernes, 9 de julio

### Plan

Capítulo 2 ¿Quiénes son tus amigos?  

- Funciones: Hablar de sus preferencias, intereses y gustos
	- 2.4.3 Gramática en contexto: Ser and estar with adjectives
	- 2.4.4 Gramática en contexto: Possessive adjectives
- Presentación del compañero (1:30 minutos) Grabar en ZOOM

### Detalles

- presentaciones
- terminar adjetivos posesivos
- empezar ser y estar

### Tarea


### Comentarios
