
## Lunes, 20 de julio

Capítulo 4 ¿Cómo es tu familia?

### Plan

4.4.2 Gramática en contexto: 
Present tense of stem-changing verbs: e → ie, o → ue, and  e → i

Funciones: Preparación Examen Oral 1

### Detalles


### Tarea


### Comentarios








## Martes, 21 de julio

Capítulo 4 ¿Cómo es tu familia?

### Plan

4.4.4 Gramática en contexto: 
Reciprocal verbs and pronouns 

Estrategias para aprender vocbulario

Preparación Examen Oral 1

### Detalles


### Tarea


### Comentarios







## Miércoles, 22 de julio

### Reunión de nivel

### Prueba oral

EDT
08:00: Nikolas
08:10: Cristina
08:20: 
08:30: Rachel
08:40: 
08:50: 
09:00: Mix
09:10: Miguel
09:20: Nick
09:30: Anna
09:40: Adam
09:50: Vince
10:00: Mary
10:10: Yifat
10:20: James
10:30: Alicia
10:40: Sarah
10:50: Yifat
11:00: Aiko
11:10: Myles
11:20: Laura
11:30: Annie
11:40: Madison
11:50: Max







## Jueves, 23 de julio

Capítulo 5 ¿Dónde vives?  

### Plan

Funciones: Descripción de lugares 

Preparación actividad e-Portafolio - Mi cuarto o lugar  preferido (1:30)

5.1.1 Vocabulario en contexto: 
¿Dónde vives?


### Detalles


### Tarea


### Comentarios







## Viernes, 24 de julio

Capítulo 5 ¿Dónde vives?  

### Plan

Funciones: Descripción de lugares 

Preparación actividad e-Portafolio - Mi cuarto o lugar  preferido (1:30)

5.4.1 Gramática en contexto: 
Present progressive


### Detalles


### Tarea


### Comentarios

