## Lunes (9 de julio)

### Plan

- El finde
- plan de esta semana

Vocabulario:

- Las diversiones, los planes

Gramática:

- gustar (de semana 1)
- presente progresivo (de semana 1)
- la hora (repaso)
- El futuro (ir a, repaso)
- Descripción de lugares
- Verbos irregulares en el presente

### Tarea

- nada

### Comentarios

- No hicimos muchos de los ejercicios que estaban 
programados para hoy
- Hay que escoger unos cuantos para mañana






## Martes (10 de julio)

### Plan

Vocabulario:

- La comida

Gramática:

- números (repaso)
- verbos irregulares (cambio de raíz y 'go')
- saber vs. conocer
- empezar por y para

### Tarea

- Buscar usos de por y para
- Estrategias para la comprensión auditiva
- NADA (2018)

### Comentarios

- Vamos atrasados. No hicimos por/para ni saber/conocer




## Miércoles (11 de julio)

### Plan

Vocabulario:

- más miembros de la familia

Gramática:

- Por y para
- Verbos de cambio radical
- ejercicios de verbos irregulares

### Tarea

- Visitar museo, preparar presentacion

### Comentarios










## Jueves (12 de julio)

Vocabulario:

- ¿Qué hacen los parientes?
- Los muebles la casa (si hay tiempo)
- La rutina (si hay tiempo)

Gramatica: 

- Verbos reflexivos
- Preparación actividad e-Portafolio - Mi cuadro preferido (1:30)

### Tarea

Preparar para presentacion 2








## Viernes (13 de julio)

### Plan

Vocabulario en contexto:

- Las rutinas familiares

Gramática:

- Reflexivos
- Tener y hacer


Presentaacion 2

### Tarea

- buscar un restaurante favorito


### Notes

Vamos muy atrasados. Aún no hemos hecho por y para (la semana que viene)
ni los verbos reflexivos