## Lunes (30 de julio)

- CAPÍTULO 8 “¡A divertirnos!”

### Plan

- Terminar palabras indefinidas/por-para
- Repaso pretérito
- Pruebita pretérito
- Paso 1
	- Vocabulario:
		- El tiempo libre
	- Gramática:
		- Repaso del pretérito
		- Estrategias para la comprensión auditiva
- Sergio Ramirez preguntas

### Tarea

- Hojas de práctica
	- por/para
- Ejercicios en línea
	- https://personal.colby.edu/~bknelson/SLC/por_para2.php
	- http://www.trinity.edu/mstroud/grammar/porpara2.htm
- Ejerecicios opcionales (pretérito)
	- CA6-14
	- CA6-15
- Diapositivas 1-11 del cap. 7




















## Martes (28 de julio)

- Paso 2

### Plan

- Prueba
- Vocabulario:
	- Las estaciones 
	- De viaje
- Gramática:
	- Imperfecto

### Tarea

- Estudiar para otra prueba del pretérito

### Comentarios

- Buen día. Estaban más atentos.


















## Miércoles (29 de julio)

### Plan

- Vocabulario:
	- Contar un cuento
- Gramática:
	- Pretérito/Imperfecto
- Preparar el cuento (2 minutos)

### Tarea

- Practicar

### Comentarios

- Bastante bien














## Jueves (30 de julio)

- Un paso más

### Plan

- Gramática:
	- El pluscuamperfecto
- Preparar el cuento (2 minutos)

### Tarea



















## Viernes (31 de julio)

### Plan

### Tarea

