
## Lunes, 20 de julio

Capítulo 4 ¿Cómo es tu familia?

### Plan

4.4.2 Gramática en contexto: 
Present tense of stem-changing verbs: e → ie, o → ue, and  e → i

Funciones: Preparación Examen Oral 1

### Detalles

- precalentamiento (mascotas)
- familia
	- repasar vocab
	- actividad del arbol geneologico
- verbos irregulares
	- repasar cambios de raíz
	- actividad de cuento
- examen oral
	- repasar pautas
	- grupos 2 dos, practicar con hoja de preguntas

### Tarea


### Comentarios








## Martes, 21 de julio

Capítulo 4 ¿Cómo es tu familia?

### Plan

4.4.4 Gramática en contexto: 
Reciprocal verbs and pronouns 

Estrategias para aprender vocbulario

Preparación Examen Oral 1

### Detalles

- actividad de precalentamiento
- se recíproco
- practicar para el examen oral 

### Tarea


### Comentarios







## Miércoles, 22 de julio

### Reunión de nivel

### Prueba oral

EDT
08:00: Nikolas
	- concordancia
	- vocabulario amplio
	- errores comunes
	- 91
08:10: Cristina
	- autocorrección ser/estar
	- uso del pasado
	- vocabulario amplio
	- 92
08:20: 
08:30: Rachel
	- concordancia (investigadore cientifio/a?)
	- mucho vocabulario, pasado, etc.
	- 95
08:40: 
08:50: 
09:00: Mix
	- buen uso del vocabulario
	- autocorreccion
	- errores de concordancia
	- 93
09:10: Miguel
	- bastante bien
	- mucha autocorreccion
	- puede centrarse en la pronunciación
	- 94
09:20: Nick
	- errrores de concordancia
	- ha mejorado bastante
	- se esta esforzando mucho
	- 90
09:30: Anna
	- errores de concordancia
	- algunas pronunciaciones raras, palabras desconocidas
	- mucho entusiasmo, ha mejorado
	- 91
09:40: Adam
	- errores básicos
	- me llamo es
	- buen esfuerzo, pero le cuesta
	- igual debería trabajar con los tutores, 
	- hay que darle ejercicios recomemdados
	- 90
09:50: Vince
	- casi igual que adam
	- cosas básicas que tiene que reforzar
	- buena actitud
	- 90
10:00: Mary
	- muy bien
	- mejoró mucho
	- autocorrección
	- errores comunes
	- 94
10:10: Yifat
10:20: James
	- muy bien
	- algunos errores comunes pero con autocorreccion
	- 92
10:30: Alicia
	- muy bien
	- algunos errores comunes
	- 94
10:40: Sarah
	- genial, pocos errores
	- 95
10:50: Yifat
	- vaya sorpresa, bastante bien
	- 91
11:00: Aiko
	- bastante bien, los errores de siempre
	- 92
11:10: Myles
	- bien
	- errores simples mellamoes
	- buena actitud
	- 92
11:20: Laura
	- mejoró mucho
	- autocorrección
	- tiene que trabajar la pronunciación
	- 92
11:30: Annie
	- muy bien
	- habra errores comunes pero no me he fijado
	- autocorreccion, buena actitud
	- 93
11:40: Madison
	- errores simples, 
	- pronunciacion schwa
	- concordancia
	- actitud positiva
	- 90
11:50: Max
	- 







## Jueves, 23 de julio

Capítulo 5 ¿Dónde vives?  

### Plan

Funciones: Descripción de lugares 

Preparación actividad e-Portafolio - Mi cuarto o lugar  preferido (1:30)

5.1.1 Vocabulario en contexto: 
¿Dónde vives?

### Detalles

- repaso kahoot de se, ser y estar, verbos en presente, verbos de cambio radical
- repasar cualquier cosa
- lluvia de ideas para describir un lugar
	- vocabulario útil?
	- temas importantes?
- Describir una casa, preposiciones básicas
- repasar pautas para la presentación 3

### Tarea


### Comentarios







## Viernes, 24 de julio

Capítulo 5 ¿Dónde vives?  

### Plan

Funciones: Descripción de lugares 

Preparación actividad e-Portafolio - Mi cuarto o lugar  preferido (1:30)

5.4.1 Gramática en contexto: 
Present progressive


### Detalles

- relaciones espaciales (preposiciones) (juego)
- el presente progresivo
- practicar para la presentación
	- grupos de 2 o 3
	- cada persona practica 1 vez
	- los demás dan retroalimentación

### Tarea


### Comentarios

