
## Lunes, 13 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

- Pronunciación
- El verbo tener
- Funciones: Narrar en el presente, describir situaciones
	- 3.1.1 Vocabulario en contexto: Las diversiones
- Preparación actividad e-Portafolio - Mi plato preferido (1:30)

### Detalles


### Tarea


### Comentarios








## Martes, 14 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

- Funciones: Narrar en el presente, describir situaciones
- 3.4.1 Gramática en contexto: Present tense of ir and ir a + infinitive
- Estrategias para la comprensión auditiva
- Preparación actividad e-Portafolio - Mi plato preferido (1:30)


### Detalles


### Tarea


### Comentarios






## Miércoles, 15 de julio

### Reunión de nivel









## Jueves, 16 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

Funciones: Narrar en el presente, describir situaciones

Presentación 
Mi plato preferido (1:30 minutos) Grabar en ZOOM

3.4.3 Gramática en contexto: 
Present tense of hacer, poner, salir, traer and oír

3.4.4 Gramática en contexto: 
Numbers 100 to 2,000,000

### Detalles


### Tarea


### Comentarios







## Viernes, 17 de julio

### Plan

Capítulo 4 ¿Cómo es tu familia?

Funciones: Narrar en el presente, describir situaciones
 
Instrucciones 
Examen Oral 1

4.1.1 Vocabulario en contexto: 
Los miembros de la familia



### Detalles


### Tarea


### Comentarios
