
## Lunes, 3 de agosto

Capítulo 7 ¿Cuál es tu deporte favorito?      

### Plan

Funciones: Entrega “Mi progreso” para e-Portafolio

Preparación actividad e-Portafolio - Preparar el proceso (1:30 minutos)

7.1.1 Vocabulario en contexto: Los deportes

### Detalles

- qué hicisteis
- precalentamiento (ejercicio pretérito)
- más práctica, verbos irregulares (hasta maya video)
- última presentación - proceso

### Tarea

### Comentarios








## Martes, 4 de agosto

Capítulo 7 ¿Cuál es tu deporte favorito?      

### Plan

Funciones: Enfatizar y clarificar la información 
Preparación actividad e-Portafolio - Preparar el proceso (1:30 minutos)

Estrategias para seguir aprendiendo español

7.4.1 Gramática en contexto: Preterit of reflexive verbs

### Detalles

- repaso de los verbos irregulares de ayer
- cancion para recordar los irregulares
- repaso tiempos verbales
- batalla naval si hay tiempo
- brainstorm ideas para el proceso

### Tarea

### Comentarios






## Miércoles, 5 de agosto

### Reunión de nivel

- moved to tuesday






## Jueves, 6 de agosto

Capítulo 7 ¿Cuál es tu deporte favorito? 

### Plan

Funciones: Hablar del pasado 
 
Selección de los mp3 para e-Portafolio

Presentación Mi proceso (1:30 minutos) Grabar en ZOOM

7.4.3 Gramática en contexto: Preterit of stem-changing -ir verbs

7.4.4 Gramática en contexto: Pronouns after prepositions

### Detalles

- repasar usos del pret.
- batalla naval
- pronouns after preps
- hablar de presentacion

### Tarea


### Comentarios








## Viernes, 7 de agosto

Capítulo 8 ¿Cuáles son tus tradiciones?

### Plan

Funciones 

Selección de los mp3 para e-Portafolio
 
8.1.1 Vocabulario en contexto: Las fiestas y las tradiciones

### Detalles

- presentacion "proceso"
- repasar pronombres con prep.
- imprefecto si hay tiempo

### Tarea


### Comentarios

