# Apuntes de clase

## Día 2 (6-30)

Vocabulario útil que vimos en clase:

- asco, asqueroso, asqueado
- sorprendido
- ocupado 
- preocupado
- desarrollar 
- crear
- construir
- el estrés ("sin estres")
- la ansiedad
- deletrear = como se escribe
- me cae bien
- me llevo bien con él/ella
- estar bueno/a
- quinientos
- soy un pesado
- estoy entre dos aguas

## Día 3 (7-1)

- la pulsera
- el bolso, la bolsa, el bolsillo
- la mochila
- tener ganas de algo
- el/la nieto/a
- el/la cuñado/a
- el/la bisabuelo/a
- la mentira 
- la verdad
- mentiroso/a

## Día 4 (7-2)

- el machismo
- machista
- ¿Qué estás haciendo ahora mismo?

## Día 5 (7-3)

- oler (huele)

## Día 6 (7-6)

- ponerse las pilas
- la llave
- el llavero
- el rincón
- la esquina
- el sótano
- el piso/la planta

## Día 7 (7-7)

- el pez
- el pelo rizado (chino)
- los rizos (chinos)
- calvo/a
- tener entrada
- una cana
- canoso
- ser una contilla
- ser chismoso
- el cotilleo
- el chisme
- cotillear/chismear

## Día 8 (7-8)

- cuñado/a
- el pez vs. el pescado
- el conejo
- la araña
- tener mala leche
- simpático/antipático
- bisabuelo
- hermanastro/padrastro/madrastra/hijastro

## Día 10 (7-14)

- Skipped día 9 sin querer
- Se me olvidó hacer la foto hoy


## Día 11 (7-15)

- skip

## Día 12 (7-16)

- Mandé un montón de ejercicios

## Día 13 (7-17)

- la confianza da asco 
- la menopausia
- Tareas
	- 5-20, p. 172*
	- 5-21, p. 174
	- 5-23, p. 175
- Repasad el vocabulario del capítulo 4, paso 1 del capítulo 5

## Día ? (7-22)

- Posibles temas para el examen oral 2
	- El fin de semana pasado
	- Mis vacaciones ideales
	- Una comparación entre países (comida/clima/etc.)
	- El programa (middlebury) vs. la vida real
	- Las actividades en Midd.
	- La comida (aquí, EE.UU., en otros países)
	- Situaciones hipotéticas
	- La importancia del español

- Vocabulario útil
	- polo/pollo/polla
	- el coño
	- el águila
	- la corbata
	- el esmoking (esmoquin)
	- pisha/shosho




