# Metas

## Josh Lesieur

- Mi primero meta en la classe es refrescar espanol que yo estudio antes.  
- Mi segundo meta es aprender pasado.  
- Y mi final meta en la classe es avanzar a las nievel 2.  


## Micaela McFadden 

- Escribir la definicíon de mis términos en español en lugar de ingles. Si yo puedes, yo entiendo bien la lingua.
- Decir mi numéro de teléfono sin pensar, pero yo sé tengo practicar MUCHO.
- Hacer unos conversiones con personas de nativo español país con menos difícil.

## Romeo Luevano

- Espero que pueda ser conversacionalmente fluido en español a la fin del verano.
- Mejorar mi escritura. 
- Aprender español suficiente para colocar en una clase de gramática de nivel superior en Swarthmore (segundario semestre de segundario año español). 

## Marley Nordmeyer

- Quiero entender el usos de los verbos hacer, ir y tener.
- Quiero entender las diferencias entre ser y estar, y por y para.
- Quiero entender y usar los verbos modales poder y deber.
- ¡Quiero comprender preguntas y frases presentado a una velocidad natural de expresión y usar el vocabulario que aprehendo en clase en conversación con fluidez!

## Sami Sehayik

- que puedo uso major los directo y indirecto objetos
- que puedo improvar entender y conjugado los verbos como ser, estar, hacer, tener, ir y haber.
- Por general espero que puedo hablar y escuchar mas facil en la idioma Espanol.

## Jordan Lavigne

- Yo quiero ser capaz a comunicarse completamente en Español.
- Yo quiero a tener un profundo la comprensión y más sólido gratitud para la cultura.
- Yo quiero a comprender todo de la Español dialectos.

## Sara McGurn

- Quiero saber correcto construcción de un frase.
- Quiero comprender los dialectos de diferente países latinos.
- Quiero estar proficiente para hablar con mi familia y compañeros.

## Louise Nielsen

- Quiero comprender la diferencia entre "ser" y "estar" y no tener que pensar en usar la conjugación correcta.
- Quiero saber las formas pretérito y futuro de los verbos regulares (-er, -ir, -ar).
- Quiero saber la forma presente (y tal vez pretérito y futuro) de los verbos muy común (como ser, estar, dar, decir).

## Rebecca Mellor

- Penser en español cuando hablo (sin traducción interno de inglés). 
- Tener un sueño en español (al menos, yo espero por más)
- Saber la pretérito (y la futuro, espero)
- Saber cuando usar vosotros 

## Andrew Hall

- Yo quiero hablar español bien.
- Yo quiero escribir con confianza en español.
- Yo quiero conocer amigos nuevos.

## Seema Marthur

- Me gustaría a tiene un fuerte conocimiento de lingual de el Espanoel que puedo utilizar construir sobre. Me gustaría por ultimo ganancia fluidez.
- Me gustaria por construir mi vocablulario, a recuerder las palabaras y  estructura de la oracion con facil.  Mi mucho deseo es a tener conversaciones con muchos personas en el mundo y transmitir mi pensamientos con claramente.
- El ultimo meta o razón es privado, pero es imporante para mi. Tengo cirugía cerebral dos anos pasada. Hay investigación aprender un nuevo idoma hacer possible crear nuevo caminos en el cerebral.  La esperanza es a compensar para areas dano.

## Max Lieblich

- Poder comprender de conversaciones naturales entre las personas des país hispanohablantes.
- Poder contribuir de manera significativo a estos conversaciones
- Poder leer los periódicas españoles sin problema.

## Will Nichol

- Yo quiero poder leer la literatura de los paises 
hispanos.
- Yo quiero poder conversar con las personas en espanol sobre de las problemas politicos.
- Yo quiero poder usar todas formas de verbos en conversacion.

## Josh (Barba roja)

- Quiero ser capaz de entender claramente. 
- Quiero ser capaz de responder adecuadamente.
- Quiero ser capaz de iniciar conversaciones con confianza y ser capaz de llevarlos a usar los términos y tiempos correctos.
