## Lunes (3 de agosto)- CAPÍTULO 8 “Somos turistas”	- Paso 1### Plan- Vocabulario:	- Por La ciudad- Gramática:	- El se pasivo 	- Los mandatos### Tarea- Ejercicios de práctica	- CA8-3, p. 148	- CA8-4, p. 148	- CA8-5, p. 149	- CA8-6, p. 150	- CA8-7, p. 150## Martes (4 de agosto)- Paso 2### Plan- Vocabulario:	- Las partes del cuerpo- Gramática:	- El subjuntivo### Tarea- Ejercicios	- CA8-8, p. 150 (las partes del cuerpo)	- CA8-10, p. 152 (el verbo doler)	- CA8-12, p. 153 (el subjuntivo)	- CA8-13, p. 153 (el subjuntivo)	- CA8-14, p. 154 (el subjuntivo)### Comentarios- Quieren aprender a poner las tildes## Miércoles (5 de agosto)- Paso 2### Plan- Vocabulario:	- Las partes del cuerpo- Gramática:	- El subjuntivo### Tarea- Ejercicios no temrinados de clase### Comentarios- La matriz = el útero## Jueves (6 de agosto)- Recordar lo del chiste- CAPÍTULO 9 “¡Así es la vida!”	- Paso 1### Plan- Vocabulario:	- Dar consejos- Gramática:	- El subjuntivo- Selección de los mp3 para e-Portafolio### Tarea## Viernes (7 de agosto)### Plan- Vocabulario:	- Dar consejos- Gramática:	- El subjuntivo### Tarea- E portafolio