# Apuntes de clase

## Día 1 (7-3)

- deletrear
- como se deletrea
- hacer una pregunta, preguntar
- vale, ¿vale?

## Día 2 (7-4)

- la tarea
- orgulloso/a
- el problema
- el género
- la cidra, la sidra
- la trama
- el pomo (de la puerta)
- una paradoja
- una contradicción
- cuadro vs. cuarto vs. cuatro
- el aula
- ocurrente
- la tilde
- el azar, al azar, aleatoriamente
- el miedo
- oscuro/a
- la sílaba
- el énfasis
- decepcionado/a
- asustar, asustado/a
- emocionado/a vs. excitado/a

## Día 3 (7-5)

- las estrellas
- tener que + inf. 
- ir a + infinitivo
- grabar, la grabación 
- hacer las paces
- mentir, una mentira
- hace falta, es necesario
- una meta, objetivo personal
- los gemelos, monozigóticos, dizigóticos, mellizos
- la arroba, @
- el comodín
- el subjuntivo 

## Día 4 (7-6)

- la concordancia 
- estar de acuerdo
- acordarse = recordar
- derramar, verter
- despertarse 
- refrán
- ingeniería, ingeniero/a
- el atril
- específico/a
- (no) tener (nada) que ver

## Día 5 (7-7)

- un acrónimo
- caerse
- llevar, llevarse
- una cinta adhesiva
- el tícket, el billete, el boleto, la entrada
- el objeto
- sonreír, la sonrisa
- reírse, la risa
- tratar de, intentar

## Día 6 (7-10)

- gritar
- caer, cayendo
- sonreír
- reírse
- las agujetas

## Día 7 (7-11)

- El estilo
	- la época
	- el propósito
	- los materiales usados
- Datos históricos
	- el autor
	- información básica
		- las fechas
		- el contexto histórico
		- la recepción por el público
- La apariencia
	- el primer plano
	- el segundo plano, el fondo
	- el ambiente
- Adjetivos
	- brillante
	- oscuro
	- vivo
	- alegre
	- triste
	- majestuoso
- Verbos/sustantivos
	- pintar
	- simbolizar/el simbolismo
	- contemplar
	- inspirar
	- la escultura
	- moldear
	- iniciar
	- componer

## Día 8 (7-12)

- No hay vocabulario
- Ejercicios (myspanishlab, bajo 'course materials')
	- la hora (cap. pre > student activities > funciones y formas 4: telling time) 
		- SAM 0P-52, SAM 0P-55
	- el presente 
		- cap. 1 > student activities > funciones y formas 1
			- SAM 01-18
			- SAM 01-19
			- SAM 01-23
		- cap. 1 > student activities > funciones y formas 2
			- SAM 01-24
			- SAM 01-28
	- ser y estar (cap. 2 > ) student activities > funciones y formas 3)
		- SAM 02-29
		- SAM 02-31
		- SAM 02-34
	- gustar (cap. 2 > student activities > funciones y formas 5)
		- SAM 02-44
		- SAM 02-45
	- saber y conocer (cap. 3 > student activities > funciones y formas 4)
		- SAM 03-36
		- SAM 03-39
	- por y para (cap. 3 > student activities > funciones y formas 5)
		- SAM 03-41
		- SAM 03-43
		- SAM 03-45
	- verbos reflexivos (cap. 4 > student activities > funciones y formas 2)
		- SAM 04-23
		- SAM 04-26
		- SAM 04-27