## Lunes (13 de julio)

CAP 4 “¡Buen provecho!”

### Plan

- Paso 1
	- Vocabulario:
		- las comidas
	- Gramática:
		- El participio pasado 
		- Complemento directo

- Estrategias para la comunicación oral
- Como preparar una presentación con elementos visuales

### Tarea

- Pensar en tu lugar favorito de Middlebury
- Participio pasado
	- Descripción gramatical: p. 338-339
	- [Ejercicio de práctica](http://conjuguemos.com/activity.php?id=23&source=public&language=spanish&type=fillin)
	- Ejercicio de práctica: GS3-1, p. 339
- Complemento Directo
	- Actividad 4-11, p. 138
	- Actividad 4-12, p. 138
- Ir vs. Irse
	- [Explicación y ejercicio](http://www.spanishdict.com/topics/show/108)
	- [Explicación](http://www.spanishdict.com/answers/116091/ir-vs-irse#.VaPE-Xj17IM)

### Comentarios

- No nos dio tiempo de terminar
- Necesitan ejercicios para practicar lso verbos reflexivos
- Hubo lío con ir vs. irse
- Hubo lío con "r" vs. "d"





















## Martes (14 de julio)

Paso 2

### Plan

- Vocabulario:
	- el mercado
- Gramática:
	- Complemento indirecto Dos complementos

<!-- - La interculturalidad: -->
	<!-- - Identificar aspectos de la interculturalidad -->

- Estrategias para la comunicación oral
	- descripción (de lo general a lo específico; del exterior al interior; de lo concreto a lo abstracto; etc)
- Como preparar una presentación con elementos visuales
- Encuesta

### Tarea

- Preparación actividad e-Portafolio - Mi lugar preferido (2:00)













## Miércoles (15 de julio)

### Plan

Presentaciones

### Tarea













## Jueves (16 de julio)

Un paso más
CAP 5 “La vida estudiantil”

### Plan

Repasar complementos directos/indirectos

- imagenes para prácticar
- jeopardy


Paso 1

- Vocabulario:
	- El horario
	- Pedir y dar opiniones Las profesiones
- Gramática:
	- El presente perfecto
	- Encantar interesar futuro

### Tarea

### Comentarios

- Vinieron a observar
- La clase estuvo bien
- No llegamos a ver la parte de vocabulario
- Hemos hecho toda gramática hasta ahora pero tienen que 
practicar más












## Viernes (17 de julio)

### Plan

- Paso 2
- Vocabulario:
	- Hablar del pasado
- Gramática:
	- 7.1 Pretérito
- Estrategias para aprender vocabulario

### Tarea




