# Semana 1

## Lunes, 29 de junio

### Plan

- Funciones: Presentaciones y despedidas
	- P.1.1 Vocabulario en contexto: Las presentaciones
	- P.1.2 Vocabulario en contexto: Los saludos y las despedidas

### Detalles

- quien soy
- estructura de la clase
	- programa
	- la semana
	- zoom
	- canvas
	- myLab
	- sugerencias para tener éxito
- quienes sois?
	- rompehielos virtual

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página moodle (go.middlebury.edu/hub)
- Estudiar el vocabulario

### Comentarios

- No se terminó el rompehielos, hay que retomar eso mañana de alguna forma
- todo más o menos bien 
- confusión en cuanto a mylab y aún hay estudiantes sin acceso a canvas






## Martes, 30 de junio

### Plan

- Funciones: Saludos, presentarse
	- P.1.6 Vocabulario en contexto: Expresiones útiles en la clase
	- P.1.7 Vocabulario en contexto: El alfabeto
	- P.4.1 Gramática en contexto: Singular forms of ser

### Detalles

- canvas, mylab, libro 
- Vocabulario útil de la clase (versión zoom)
- Saludos, presentarse, despedirse (whiteboard)
- verbo ser
- alfabeto (que lo revisen en casa)

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página moodle (go.middlebury.edu/hub)
- Estudiar el vocabulario

### Comentarios

- Bastante bien
- Hay que jugar más con la pizarra interactiva (para que todo el mundo la puede usar)
- breakout rooms molan






## Miércoles, 1 de julio

### Reunión de nivel

- qué tal los primeros días?
	- zoom
	- canvas
	- mylab
- zoom channel
	- para las clases
	- para nosotros
- horario para las reuniones
- oratory coaching 
	- 6 de julio
- Mesa redonda - Racismo, lenguaje y comunidad
	- hay que invitar a los de 1 para hablar (a la 1:30)




## Jueves, 2 de julio

### Plan

- Funciones: Entrevistas y presentaciones 
- Estrategias para aprender vocabulario
	- 1.1.1 Vocabulario en contexto: Los estudiantes españoles 

### Detalles

- canvas, mylab check
- zoom chat
- entrevistas
	- lluvia de ideas, preguntas para una entrevista
	- preguntas acerca de la escuela en otros países
	- invitado especial
- estrategias para aprender vocabulario
	- break out rooms
	- google doc trick 
		=GOOGLETRANSLATE(CELL, "en", "es")

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página moodle (go.middlebury.edu/hub)
- Estudiar el vocabulario

### Comentarios

- La entrevista con Rocio funcionó muy bien
- vocab strategies funcionó muy bien también

 
            


## Viernes, 3 de julio

### Plan

- Funciones: La descripción de personas
- Actividad e-Portafolio - Cómo se hace una presentación
	- 1.4.1 Gramática en contexto: Interrogative words
	- 1.4.2 Gramática en contexto: Present tense of estar 

### Detalles

- ahorcado (pizarra interactiva)
- palabras interrogativas (breakout rooms)
- estar (ppt)
- como se hace una presentación (lluvia de ideas, whiteboard, ppt de la clinica)

### Tarea

- Usar lo que han visto esta semana en una actividad co-curricular
- estudiar vocabulario

### Comentarios


