---
output: word_document
---

### Nombre:  

### Instrucciones

Martín le escribe una carta a su mejor amigo Javier para contarle lo que hizo durante el fin de semana en la Escuela Española de Middlebury College. Conjuga los verbos en el pretérito.

Hola Javier,

Ya llevo 3 semanas en la Escuela Española y creo que he aprendido mucho. El fin de semana pasado \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (1. estar) genial. El viernes por la noche mis amigos y yo fuimos a un concierto de poesía y jazz. A mí no \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (2. gustar (me)) mucho la poesía, pero los músicos \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (3. tocar) muy bien. Después, \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (4. caminar (yo)) al Grill para tomar un batido de chocolate. \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (5. encontrarse (yo)) con unos amigos de mi clase de Comunicación y \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (6. salir (nosotros)) para Dos Hermanos. El sábado por la noche \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (7. cantar (yo)) una canción en español en la fiesta de karaoke. Luego, \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (8. beber) dos o tres cervezas y \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (9. regresar) a mi habitación. Fue un fin de semana divertido. Espero que el siguiente sea igual. 

Un saludo,  
Martín


### Nombre:  

### Instrucciones

Martín le escribe una carta a su mejor amigo Javier para contarle lo que hizo durante el fin de semana en la Escuela Española de Middlebury College. Conjuga los verbos en el pretérito.

Hola Javier,

Ya llevo 3 semanas en la Escuela Española y creo que he aprendido mucho. El fin de semana pasado \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (1. estar) genial. El viernes por la noche mis amigos y yo fuimos a un concierto de poesía y jazz. A mí no \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (2. gustar (me)) mucho la poesía, pero los músicos \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (3. tocar) muy bien. Después, \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (4. caminar (yo)) al Grill para tomar un batido de chocolate. \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (5. encontrarse (yo)) con unos amigos de mi clase de Comunicación y \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (6. salir (nosotros)) para Dos Hermanos. El sábado por la noche \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (7. cantar (yo)) una canción en español en la fiesta de karaoke. Luego, \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (8. beber) dos o tres cervezas y \_\_\_\_\_\_\_\_\_\_\_\_\_\_ (9. regresar) a mi habitación. Fue un fin de semana divertido. Espero que el siguiente sea igual. 

Un saludo,  
Martín