
## Lunes, 12 de julio

### Plan

Narrar en el presente, 
describir situaciones, 
participio presente

### Detalles

- actividad de precalentamiento
- Pronunciación
- El verbo tener
- Mi plato preferido
	- pautas para la presentación
	- tiempo para practicar (escoger comida, lluvia de ideas sobre el vocabulario necesariop)

### Tarea

- practicar/preparar presentación 2

### Comentarios

- no me dio tiempo hacer lo del verbo tener (para el martes)







## Martes, 13 de julio

### Plan

Complemento directo

### Detalles

- Más gustar
- El verbo tener
- Ir e ir a + inf. 
- ensayar presentación

### Tarea

- bien
- hicimos todo

### Comentarios

- mucha gramática al final, pero bien





## Miércoles, 14 de julio

Demostrativos







## Jueves, 15 de julio

### Plan

Objeto indirecto

### Detalles

- presentaciones
- verbos -go
- hablar de números

### Tarea


### Comentarios







## Viernes, 16 de julio

### Plan

Examen oral

### Detalles

- Grabaciones
	- P1seccionC!, P2seccionC!
	- P1seccionB!, P2seccionB!
- repasar verbos go (resaltar semejanzas con decir, tener)
- los números (actividad de práctica)
- la familia (vocab y actividad)
- hablar de examen oral
	- qué hacemos?
	- cuándo? (horario el miércoles)

### Tarea

- NA

### Comentarios

- Apenas hablamos de la familia
