
## Lunes, 27 de julio

Capítulo 5 ¿Dónde vives?  

### Plan

Funciones: Señalar e identificar lugares lugares 

Presentación  Mi cuarto o lugar preferido (1:30 minutos) Grabar en ZOOM

5.4.3 Gramática en contexto: Direct object nouns and pronouns

### Detalles

- precalentamiento (presente progresivo)
- presentaciones
- complementos directos

### Tarea


### Comentarios








## Martes, 28 de julio

Capítulo 6 ¿Qué te gusta comprar?  

### Plan

Funciones 

Preparación y Selección de los mp3 para e-Portafolio – Mi progreso

Estrategias para la lectura

6.1.1 Vocabulario en contexto: Las compras


### Detalles

- e-Portafolio
	- ver temario para mostrar lo que es
	- enseñarles cómo llegar a google drive
	- preguntar por grabaciones de Laura y Vince
- DO

### Tarea


### Comentarios






## Miércoles, 29 de julio

### Reunión de nivel

Hablar con Aiko
	
- que participe en la intervención de la mesa redonda
- que hable un minuto sobre su experiencia con la lengua, el multilingüismo, el biculturalismo, translenguaje

Comentar lo de las intervenciones a las de 1

Informarle a Jacobo que la mesa tiene que ser a las 3






## Jueves, 30 de julio

Capítulo 6 ¿Qué te gusta comprar?  

### Plan

Funciones: Expresar gustos y preferencias
 
Preparación y Selección de los mp3 para e-Portafolio – Mi progreso

6.4.1 Gramática en contexto: More about ser and estar

6.4.2 Gramática en contexto: Indirect object nouns and pronouns


### Detalles

- calentar con img de cap. 5 (DO)
- CI
- CD CI
- e portafolio
	- cuál es un ejemplo bueno? Brainstorm

### Tarea


### Comentarios








## Viernes, 31 de julio

Capítulo 6 ¿Qué te gusta comprar?  

### Plan

Funciones y formas: Acciónes el pasado

Entrega Selección de los mp3 para e-Portafolio – Mi progreso

6.4.4 Gramática en contexto: Preterit tense of regular verbs

### Detalles

- precalentamiento
	- kahoot CD
	- repasar ID
	- images
	- situación 3
- pretérito
- preguntas sobre el e portafolio

### Tarea


### Comentarios


