# Semana 1

## Lunes, 28 de junio

### Plan

Mosaicos Cap. 1 (includes prelim.)
Preliminar 1: Bienvenidos  

- Funciones y formas: 
  - Presentaciones y despedidas
  - Descripciones de personas
  - presente

### Detalles

- quien soy
- estructura de la clase
	- programa
	- la semana
	- zoom
	- canvas
	- myLab
	- sugerencias para tener éxito
- quienes sois?
	- rompehielos virtual
- Presentación de Cap. prelim. (primeras diapositivas)
	- presentarse
	- descripción con ser
	- (saltar "vocab útil")

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página canvas (go.middlebury.edu/hub)

### Comentarios

- No llegamos a terminar (como siempre)







## Martes, 29 de junio

### Plan

Mosaicos Capítulo 1 (cap. prelim.)

- Artículos y sustantivos, 
- estar

### Detalles

- Del lunes... el verbo ser
- Vocabulario básico de la clase 
	- actividad (¿qué ves? ¿qué es?)
- Los sustantivos
	- género
	- número
- Los artículos
	- definidos
	- indefinidos
	- actividades p1 y p2
- DESCANSO
- El abecedario
	- el ahoracado
- Los números
	- actividad p4
- Hasta 18 de cap. 1 (si puedes)

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página canvas
- Estudiar el vocabulario

### Comentarios

- 









## Miércoles, 30 de junio

### Plan

- Hasta diapositiva 63 (empezando en la 31)

Gramática:

- Pronombres personales
- verbos: Estar, ser, tener, ir

### Tarea (opcional, por myspanishlab)

- Usar **estar**, **ser**, **tener** e **ir** en conversaciones reales
- Estudiar el vocabulario
- Ejercicios opcionales
	- Vocabulario en contexto
		- TXT 0P-05, 0P-16
		- SAM 0P-21, 0P-22, 0P-23, 0P-26
	- Funciones y formas: 1
		- SAM 0P-36, 0P-37

- Repasar los pronombres personales
- Repasar 'tarea', verbos (ser, estar, tener, ir), actividad
- Paso 2  
- Vocabulario:
	- La familia

- Gramática:
	- Posesión
	- Verbos regulares

- Cómo presentar a un amigo
	- enseñar la rúbrica
	- se permite una tarjeta
- Cómo se graba un mp3


### Tarea

- Presentación de un compañero

### Comentarios











## Jueves, 2 de julio

### Plan

Capítulo 1 ¿Qué estudias?  

- Funciones: Entrevistas y presentaciones 
- Estrategias para aprender vocabulario
	- 1.1.1 Vocabulario en contexto: Los estudiantes españoles 

### Detalles

- canvas, mylab check
- zoom chat
- entrevistas
	- lluvia de ideas, preguntas para una entrevista
	- preguntas acerca de la escuela en otros países
	- invitado especial
- estrategias para aprender vocabulario
	- break out rooms
	- google doc trick 
		=GOOGLETRANSLATE(CELL, "en", "es")

### Tarea

- Apuntarse al mylab/libro
- Repasar el programa
- Explorar la página moodle (go.middlebury.edu/hub)
- Estudiar el vocabulario

### Comentarios

- La entrevista con Rocio funcionó muy bien
- vocab strategies funcionó muy bien también

 
            


## Viernes, 3 de julio

### Plan

Capítulo 1 ¿Qué estudias?  

- Funciones: La descripción de personas
- Actividad e-Portafolio - Cómo se hace una presentación
	- 1.4.1 Gramática en contexto: Interrogative words
	- 1.4.2 Gramática en contexto: Present tense of estar 

### Detalles

- ahorcado (pizarra interactiva)
- palabras interrogativas (breakout rooms)
- estar (ppt)
- como se hace una presentación (lluvia de ideas, whiteboard, ppt de la clinica)

### Tarea

- Usar lo que han visto esta semana en una actividad co-curricular
- estudiar vocabulario

### Comentarios

- hablar de la concordancia el lunes
- hablar de office hours tb 

