
## Lunes, 11 de agosto

Capítulo 8 ¿Cuáles son tus tradiciones?

### Plan

- Funciones: Describir en el pasado
- Entrega del e-Portafolio
- Instrucciones Examen Oral 
- 8.4.1 Gramática en contexto: The imperfect

### Detalles

- que tal el finde
- examen final (doc, orden)
- tarea: reflexión sobre 3 metas (del principio del verano)
	- conseguiste las metas? Por qué sí? Por qué no?
	Qué harías diferente? Qué funcionó para ti?
- imperfecto
- 10 minutos para las evaluaciones

### Tarea

### Comentarios








## Martes, 12 de agosto

Capítulo 8 ¿Cuáles son tus tradiciones?

### Plan

- Funciones: Narrar en el pasado
- Preparación Examen Final
- Estrategias para seguir aprendiendo español
- 8.4.2 Gramática en contexto: The preterit and the imperfect

### Detalles

- imperfecto/pretérito
- estrategias para seguir aprendiendo español
- último kahoot
- práctica para la prueba final

### Tarea

### Comentarios






## Miércoles, 13 de agosto

### Reunión de nivel







## Jueves, 14 de agosto

### Plan

### Detalles

### Tarea

### Comentarios





