 ## Lunes (3 julio)

### Sección

- Intro al curso
- Mosaicos cap. preliminar, 1, 2

### Plan

- Me presento
- Intro al curso
	- el programa
	- la semana
	- moodle
	- sugerencias para tener éxito
- Para sobrevivir
	- presentarse, instrucciones, hablar con el profesor

(hasta aquí)

### Tarea

- Comprar el libro
- Repasar el programa
- Explorar la página moodle (go/hub/)
- Estudiar el vocabulario

### Comentarios

No llegamos a terminarlo todo. Vimos los artículos y paramos
antes de practicar el abecedario. Esta información también 
está incluída en la primera parte de la presentación del 
capítulo 1 (o sea se puede pasar a la siguiente presentación).


## Martes (4 julio)

### Del lunes... (cap. preliminar, 1)

- Vocabulario básico de la clase 
	- actividad (¿qué ves? ¿qué es?)
- DESCANSO
- Los sustantivos
	- género
	- número
- Los artículos
	- definidos
	- indefinidos
	- actividades p1 y p2
- DESCANSO
- El abecedario
	- el ahoracado
- Los números
	- actividad p4
- Hablar del experimento

Vocabulario:

- Saludos
- Origen
- Información básica

- **Experimento**


### Comentarios

No he terminado. Este grupo hace muchas preguntas. Hablamos del verbo 
estar. Mañana veremos tener, ser e ir. 



## Miércoles (5 julio)

### Plan

- Hasta diapositiva 63 (empezando en la 31)

Gramática:

- Pronombres personales
- verbos: Estar, ser, tener, ir

### Tarea

- Usar **estar**, **ser**, **tener** e **ir** en conversaciones reales
- Estudiar el vocabulario
- Ejercicios opcionales
	- Vocabulario en contexto
		- TXT 0P-05, 0P-16
		- SAM 0P-21, 0P-22, 0P-23, 0P-26
	- Funciones y formas: 1
		- SAM 0P-36, 0P-37

- Repasar los pronombres personales
- Repasar 'tarea', verbos (ser, estar, tener, ir), actividad
- Paso 2  
- Vocabulario:
	- La familia

- Gramática:
	- Posesión
	- Verbos regulares

- Cómo presentar a un amigo
	- enseñar la rúbrica
	- se permite una tarjeta
- Cómo se graba un mp3


### Tarea

- Presentación de un compañero

### Comentarios

De nuevo no terminé todo, pero van progresando. 
Mañana hay que hablar de los adjetivos posesivos. 
Hay que darles más tiempo para que practiquen las 
presentaciones y para que terminen de recoger la 
información de su compañero/a







## Jueves (6 de julio)

### Plan

- Paso 3
- Vocabulario:
	- El tiempo libre

- Gramática:
	- Gustar
	- Preguntas
	- El presente progresivo

- Presentación del compañero (1:30 minutos)

### Tarea

practicar, ir a visitar el museo

### Comentarios

Hoy por fin llegué a terminar todo lo que quería 
hacer. Mañana tienen sus presentaciones y hablaremos 
del verbo gustar 








## Viernes (7 de julio)

### Plan

- Repasito
- CAPÍTULO  2 “¡De viaje!”  

- Paso 1 
- Vocabulario:
	- Horarios
	- fechas; de viaje

- Gramática:
	- Verbos de cambio radical




### Tarea



### Comentarios

Todo bien. Han hecho las presentaciones, pero SansSpace no está 
funcionando muy bien todavía, por lo que aún no tienen que subir 
correcciones. He seguido el plan de esta semana prácticamente a 
pie de la letra. 

