## Lunes (6 de julio)

Puentes 2.2

### Plan

- El finde
- plan de esta semana
- SansSpace

Paso 2

Vocabulario:

- El hotel
- más números

Gramática:

- Verbos irregulares 
- El futuro
- Estrategias para la comprensión auditiva

### Tarea

- nada

### Comentarios

- No hicimos muchos de los ejercicios que estaban 
programados para hoy
- Hay que escoger unos cuantos para mañana















## Martes (7 de julio)

CAPÍTULO 3 “Entre familia” - Paso 1

### Plan

Vocabulario:

- descripciones

Gramática:

- Adjetivos comparativos

### Tarea (opcional)

- CA3-1, p. 41
- CA3-5, p. 43
- CA3-6, p. 43
- CA3-8, p. 44-45

### Comentarios

- No terminamos el último ejercicio
- Hay que mirarlo al comienzo de la clase mañana









## Miércoles (8 de julio)

Paso 2

### Plan

Vocabulario:

- La familia 

Gramática:

- Ser y estar
- Estrategias para la comunicación oral
- Instrucciones Examen Oral 1

### Tarea

### Comentarios

- Todo bien. Dejé dos actividades para mañana









## Jueves (9 de julio)

Paso 2/3

### Plan

Paso 3

Vocabulario:

- Los muebles la casa
- La rutina

Gramática:

- Reflexivos
- El participio pasado

Preparación Examen Oral 1: individual (capítulos 1,2 y 3)

### Tarea

Preparar para examen oral 1








## Viernes (10 de julio)

### Plan

Examen oral 1

### Tarea

Correcciones de la prueba oral 1


