 ## Lunes (29 junio)

### Sección

- Intro al curso
- Puentes Paso Preliminar

### Plan

- Me presento
- Intro al curso
	- el programa
	- la semana
	- moodle
	- sugerencias para tener éxito
- Para sobrevivir
	- presentarse, instrucciones, hablar con el profesor
	- p5
- Vocabulario básico de la clase (conseguir imagen de la p. 2)
	- actividad (¿qué ves?¿qué es?)
- DESCANSO
- Los sustantivos
	- género
	- número
- Los artículos
	- definidos
	- indefinidos
	- actividades p1 y p2
- DESCANSO
- El abecedario
	- el ahoracado
- Los números
	- actividad p4
- Hablar del experimento

### Tarea

- Comprar el libro
- Repasar el programa
- Explorar la página moodle (go/hub/)
- Estudiar el vocabulario

### Comentarios

No llegamos a terminarlo todo. Vimos los artículos y paramos
antes de practicar el abecedario. Esta información también 
está incluída en la primera parte de la presentación del 
capítulo 1 (o sea se puede pasar a la siguiente presentación).





## Martes (30 junio)

### Sección

- Puentes Capítulo 1.1 “Así somos”

### Plan

- Repasar moodle
- Repasar los sustantivos, las letras y los números
- Paso 1 

Vocabulario:

- Saludos
- Origen
- Información básica

Gramática:

- Pronombres personales
- verbos: Estar, ser, tener, ir

<!-- La interculturalidad: El YO intercultural -->

### Tarea

- Usar **estar**, **ser**, **tener** e **ir** en conversaciones reales
- Estudiar el vocabulario
- CA1-7, CA1-8 (opcional)

- **Experimento**

<!-- dos personas después de clase, una persona por la tarde -->

### Comentarios

Todo bien. No terminamos las actividades relacionadas con los verbos ser, estar, 
tener e ir. Lo haremos mañana primera cosa. 






## Miércoles (1 julio)

### Sección: 

- Puentes Capítulo 1.2

### Plan

- Repasar los pronombres personales
- Repasar 'tarea', verbos (ser, estar, tener, ir), actividad
- Paso 2  
- Vocabulario:
	- La familia

- Gramática:
	- Posesión
	- Verbos regulares

- Estrategias para la comunicación oral  
- Cómo presentar a un amigo
	- enseñar la rúbrica
	- se permite una tarjeta
- Cómo se graba un mp3 (actividad e-Portafolio)
	- enseñar sanspace


### Tarea

- Presentación de un compañero

### Comentarios

Se dejaron las dos últimas actividades para mañana (jueves). 
Las presentaciones van bien y se harán al final de la clase 
de mañana. 







## Jueves (2 julio)

### Sección: 

- Puentes Capítulo 1.3

### Plan

- Paso 3
- Vocabulario:
	- El tiempo libre

- Gramática:
	- Gustar
	- Preguntas
	- El presente progresivo

<!-- La interculturalidad: Identificar aspectos de la interculturalidad   -->

- Presentación del compañero (1:30 minutos)

### Tarea

- Grabar un mp3 (actividad e-Portafolio) 

<!-- si hay tiempo se cubre en clase -->









## Viernes (3 julio)

### Sección: 

- Puentes Capítulo 2.1

### Plan

- Repasito
- SansSpace
- CAPÍTULO  2 “¡De viaje!”  

- Paso 1 
- Vocabulario:
	- Horarios
	- fechas; de viaje

- Gramática:
	- Verbos de cambio radical

- Estrategias para la comprensión auditiva



### Tarea

- Tarea (opcional)
	- CA1-15, CA1-16, CA1-17

### Comentarios

Todo bien. Han hecho las presentaciones, pero SansSpace no está 
funcionando muy bien todavía, por lo que aún no tienen que subir 
correcciones. He seguido el plan de esta semana prácticamente a 
pie de la letra. 

