## Lunes (10 de julio)

### Plan

- El finde
- plan de esta semana

Vocabulario:

- El hotel
- más números

Gramática:

- Verbos irregulares 
- El futuro (ir a)
- Estrategias para la comprensión auditiva

### Tarea

- nada

### Comentarios

- No hicimos muchos de los ejercicios que estaban 
programados para hoy
- Hay que escoger unos cuantos para mañana


<!-- 
verbos irregulares
ir a + infinitivo
-->


## Martes (11 de julio)

### Plan

Vocabulario:

- viajes

Gramática:

- verbos irregulares (cambio de raíz y 'go')
- más gustar
- más números
- saber vs. conocer
- empezar por y para

### Tarea

- Buscar usos de por y para





## Miércoles (8 de julio)

### Plan

Vocabulario:

- la comida

Gramática:

- Por y para
- ejercicios de verbos irregulares

### Tarea

### Comentarios










## Jueves (9 de julio)

Vocabulario:

- Los muebles la casa
- La rutina



### Tarea

Preparar para presentacion 2








## Viernes (10 de julio)

### Plan

Gramática:

- Reflexivos
- Ser y estar

Presentaacion 2

### Tarea



