## Lunes (2 julio)

### Sección

- Intro al curso
- Mosaicos cap. preliminar, 1, 2

### Plan

- Pasar lista
- Me presento
- Intro al curso
	- el programa
	- la semana
	- moodle
	- sugerencias para tener éxito

(hasta aquí)

- Para sobrevivir
	- presentarse, instrucciones, hablar con el profesor


### Tarea

- Comprar el libro
- Repasar el programa
- Explorar la página moodle (go/hub/)
- Estudiar el vocabulario

### Comentarios

No llegamos a terminarlo todo. Vimos los artículos y paramos
antes de practicar el abecedario. Esta información también 
está incluída en la primera parte de la presentación del 
capítulo 1 (o sea se puede pasar a la siguiente presentación).





## Martes (3 julio)

### Del lunes... (cap. preliminar, 1)

El libro: 
CourseID: CRSKLGK-645943
Course Name: Recursos para la comunicación - 1.5 - Verano 2018
Description:
Text book Title: Mosaicos: Spanish as a World Language, 6e
Text book ISBN: 020525540X-9780205255405


- Vocabulario básico de la clase 
	- actividad (¿qué ves? ¿qué es?)
- DESCANSO
- Los sustantivos
	- género
	- número
- Los artículos
	- definidos
	- indefinidos
	- actividades p1 y p2
- DESCANSO
- El abecedario
	- el ahoracado
- Los números
	- actividad p4

Vocabulario:

- Saludos
- Origen
- Información básica


### Comentarios

No he terminado. Este grupo hace muchas preguntas. Hablamos del verbo 
estar. Mañana veremos tener, ser e ir. He reestructurado las presentaciones 
para que vayan según el capítulo del libro y no por semanas. 








## Miércoles (4 julio)

### Plan

- Hasta diapositiva 63 (empezando en la 31)

Gramática:

- Pronombres personales
- verbos: Estar, ser, tener, ir

### Tarea (opcional, por myspanishlab)

- Usar **estar**, **ser**, **tener** e **ir** en conversaciones reales
- Estudiar el vocabulario
- Ejercicios opcionales
	- Vocabulario en contexto
		- TXT 0P-05, 0P-16
		- SAM 0P-21, 0P-22, 0P-23, 0P-26
	- Funciones y formas: 1
		- SAM 0P-36, 0P-37

- Repasar los pronombres personales
- Repasar 'tarea', verbos (ser, estar, tener, ir), actividad
- Paso 2  
- Vocabulario:
	- La familia

- Gramática:
	- Posesión
	- Verbos regulares

- Cómo presentar a un amigo
	- enseñar la rúbrica
	- se permite una tarjeta
- Cómo se graba un mp3


### Tarea

- Presentación de un compañero

### Comentarios

De nuevo no terminé todo, pero van progresando. 
Mañana hay que hablar de los adjetivos posesivos. 
Hay que darles más tiempo para que practiquen las 
presentaciones y para que terminen de recoger la 
información de su compañero/a







## Jueves (5 de julio)

### Plan

- Paso 3
- Vocabulario:
	- El tiempo libre

- Gramática:
	- Gustar
	- Preguntas
	- El presente progresivo

- Presentación del compañero (práctica, 1:30 minutos)

### Tarea

practicar, ir a visitar el museo

### Comentarios

Hoy por fin llegué a terminar todo lo que quería 
hacer. Mañana tienen sus presentaciones y hablaremos 
del verbo gustar 








## Viernes (6 de julio)

### Plan

- Repasito
- CAPÍTULO  2 “¡De viaje!”  


- PRESENTACIONES

- Gramática:
	- los adjetivos
	- los adjetivos posesivos

### Tarea


### Comentarios

Todo bien. Han hecho las presentaciones. No llegué 
a hablar del verbo gustar. O sea sigo atrasado pero 
todo bien. 

