---
title: "Programa"
output:
  html_document:
    toc: true
---



3151 – High Beginner Spanish in Context – Horario 8:00-9:50am

|                    | Sección A               | Sección B              | Sección C               |
|:-------------------|:------------------------|:-----------------------|:------------------------|
| Aulas de clase     | TBA                     |   TBA                  | TBA                     |
| Profesores         | Ana María Wiseman       | Ana Laura Brophy       | Joseph Casillas         |
| Correo electrónico | awiseman@middlebury.edu | abrophy@middlebury.edu | jcasilla@middlebury.edu |

## Descripción del curso

Este curso se ofrece para estudiantes que han tenido algún contacto previo con el español, algún estudio formal, alguna experiencia en un país hispano-hablante, el estudio de alguna otra lengua romance. Se trabaja para desarrollar y controlar las estructuras básicas de gramática tanto como la adquisición léxica.   Los estudiantes consolidad la habilidad de negociar situaciones básicas en español dentro de un contexto cultural y se preparan para estudiar la lengua independientemente. Las nuevas funciones se presentan a través de actividades que hacen hincapié en las destrezas orales y de comprensión auditiva y preparan al estudiante para las actividades en los otros cursos del nivel 1.5. El conocimiento cultural es un aspecto fundamental para llegar a comprender la comunicación entre hispano-hablantes de varias culturas.. El curso se reúne dos horas diarias. (1 unidad de crédito)

## Objetivos del curso

Al final de este curso los estudiantes podrán realizar las siguientes funciones verbales usando un español idiomático y apropiado para el contexto social y el interlocutor específico:

- describir experiencias de la vida diaria (rutinas, actividades, etc.)
- describir personas (familia, amigos, etc.) y lugares
- narrar eventos en los tiempos del presente y del futuro (y de manera limitada en el pasado)
- describir y reflexionar sobre los contrastes culturales entre culturas de habla inglesa y de habla española (tradiciones, feriados, asuntos sociales, etc.) 
- hacer preguntas para solicitar información sobre temas culturales de interés general 
- presentar a la clase temas investigados y contestar preguntas
- dar instrucciones y direcciones en forma limitada

## Materiales para el curso

- Puentes: Spanish for Intensive and High Beginner Courses. 6th edition (2013). Marinelli, Patti J. and Laughlin, Lizette Mujica. Heinle.
- Puentes: Student Activity Manual. 6th edition (2013). Marinelli, Patti J. and Laughlin, Lizette Mujica. Heinle.
- Materiales en internet a través de go/hub 

### Materiales recomendados:

- Un diccionario bilingüe como por ejemplo: Diccionario Oxford Compacto 
- Herramientas de Microsoft Word en español

## Metodología

Las clases incluyen, además de la presentación por parte del profesor de los materiales nuevos, una variedad de actividades destinadas fundamentalmente a la práctica oral del español: diálogo en parejas o grupos pequeños, breves presentaciones individuales, ejercicios de pronunciación, improvisaciones a partir de situaciones dadas, debates, reportajes y entrevistas. Los estudiantes deben preparar previamente los materiales nuevos asignados para cada día (memorización del vocabulario nuevo, estudio de verbos u otras formas gramaticales) y hacer los ejercicios correspondientes del libro de actividades.

## La palabra de honor

Para leer más información sobra la palabra de honor: http://www.middlebury.edu/academics/ls/pledge/.

> Compromiso de Lengua
Al firmar este Compromiso de Lengua, entiendo que, si bien mi competencia en la lengua española es limitada, haré mi mayor esfuerzo por seguir la letra y espíritu del compromiso, tal como está definido por mi escuela. Entiendo que el fallo en el cumplimiento de este Compromiso de Lengua puede resultar en mi expulsión de la escuela sin crédito o reembolso alguno. Respetaré el Compromiso de Lengua tomado por otros estudiantes en mi escuela y no hablaré inglés en su presencia. Firmaré el Compromiso de lengua en el momento que lo determine la directora de mi escuela y entonces usaré únicamente el español como mi única lengua de comunicación, mientras asista a la Escuela de Lengua de Middlebury.

## Normas del curso

- Ausencias. La asistencia a las clases diarias es obligatoria. Ante cualquier inconveniente, deberá ponerse en contacto con el instructor y con Roberto Veguez, Director Asistente para Asuntos No Académicos (veguez@middlebury.edu). Por cada ausencia no justificada, se reducirá en dos puntos (2) la nota final del curso”.
- Plagio y autoplagio. (ver www.middlebury.edu/about/handbook/student_policies/ Academic_Disciplinary_Policies)
- Plagio: Todo material (texto e ideas) que viene de fuentes secundarias (bibliografía) que se utilice en un texto o proyecto preparado por el estudiante debe estar documentado según las normas del MLA. La falta de referencia al material citado o parafraseado se considerará plagio. Estos casos serán reportados al Consejo Universitario y tendrán como consecuencia una “F” en el curso. 
- Auto-plagio: Todo trabajo que haya sido considerado como crédito para un curso dado no será considerado válido para otro, tanto dentro del mismo periodo académico, como en uno posterior. No habrá excepciones a esta regla. Repetir el trabajo de un curso en otro tendrá como consecuencia la reprobación inmediata del segundo curso. Si los trabajos de dos cursos diferentes estuvieran relacionados de algún modo, y el estudiante tuviera alguna duda respecto de la legalidad del segundo proyecto, éste deberá discutir sobre el asunto con todos los instructores involucrados. De este modo se evitará cualquier posible, e inadvertida, trasgresión a la regla.
- Tutorías. La profesora estará disponible para contestar preguntas relacionadas con los contenidos o materiales del curso en las horas y lugares concertados entre el profesor y el estudiante. Asimismo, los alumnos pueden trabajar con las tutoras de la Escuela Española, disponibles de lunes a viernes entre de 9-11am y de lunes a jueves de 4:30-6:30pm en las oficinas 201 (Eva Lea) y 202 (Marta Vacas) en Milliken. Los estudiantes interesados en una tutoría deben pasar por las oficinas para apuntar su nombre en las horas de oficina. Las citas duran 20 minutos. Es posible conseguir una tutoría sin cita previa si el horario es disponible. Recuerden que las tutoras pueden ayudar a comprender puntos gramaticales ya estudiados en clase, revisar textos escritos u orales, y realizar ejercicios para mejorar la pronunciación. Las tutoras no hacen las tareas asignadas a los estudiantes. 
- Diversidad. Los materiales y textos usados en esta clase han sido escogidos con criterio y fines estrictamente pedagógicos. Dichos criterios están de acuerdo con los objetivos pedagógicos de esta clase en particular y con los principios de diversidad de Middlebury College. Los contenidos expresados en estos materiales no reflejan necesariamente la opinión de este instructor ni de la Escuela Española y han sido seleccionados para ser analizados críticamente. En el caso de que un estudiante se sienta ofendido por el contenido de este material pedagógico, por favor, hágamelo saber inmediatamente. Escucharé personalmente sus opiniones, comentarios y sugerencias. De esta manera, podremos ponernos de acuerdo acerca de cómo proceder en este asunto. El objetivo es lograr que incluso esta experiencia se transforme en un elemento más en nuestro diálogo crítico acerca de los materiales de la clase y las culturas en que se generan y en las que nos encontramos aquí en Middlebury. 
- Asistencia individual. Si usted sufre de alguna discapacidad documentada, y requiere algún arreglo especial, por favor informe cuanto antes a su instructor. Si usted experimenta dificultades en el aprendizaje, busque ayuda inmediatamente en el Student Accessibility Services (Meeker House, tel. 802-443-5936).

## Escala de notas

<div align="center">

|                 |                      |                  |       |
|:----------------|:---------------------|:-----------------|:------| 
| A &nbsp; &nbsp; | 94-100 &nbsp; &nbsp; | C+ &nbsp; &nbsp; | 77-79 |
| A-              | 90-93                | C                | 74-76 |
| B+              | 87-89                | C-               | 70-73 |
| B               | 84-86                | D                | 64-69 |
| B-              | 80-83                | F                | 0-64  |

</div>

## Evaluación

```{r, results = 'asis', echo = FALSE}
library(pander)
df <- data.frame(
                 Área = c("PREPARACIÓN: portafolio oral, tarea, participación, pruebitas", "EXÁMENES ORALES"),
                 Porcentaje = c("40%", "60%"),
                 Detalles = c("La realización de las tareas diarias, la preparación de los materiales asignados participación, para cada día y la participación en clase son fundamentales para el progreso y la satisfactoria consecución de los objetivos del curso. Cada semana habrá una o varias \"pruebitas sorpresa\", que permitirán valorar ese trabajo diario de los estudiantes. El estudiante irá creando un portafolio electrónico individual con los materiales que vaya elaborando a lo largo del curso. Este portafolio le permitirá examinar su proceso de aprendizaje y progreso (mediante el autoanálisis) y constituirá otro instrumento importante de evaluación para el instructor. El 40% de la nota final estará determinado por este trabajo diario de la tarea, participación en clase, pruebitas y portafolio.", "A lo largo del curso se realizarán tres exámenes orales, que tendrán un valor del 60% de la nota final (el 20% cada uno de ellos). Estos exámenes (que serán grabados para facilitar su calificación) incorporarán los aspectos vistos en clase: gramática y vocabulario en contexto. Las pautas para la preparación de estos exámenes y los criterios para su evaluación se explicarán con la anticipación suficiente. Dos entrevistas individuales con tu profesora, con preguntas y respuestas preparadas. Un examen con un/a compañer@ de clase.")
)
pandoc.table(df, justify = c('left', 'left', 'left'), split.cells = c(5, 5, 42))
```


## Sugerencias para un aprendizaje mejor 

- Habla siempre español 
- Haz muchas preguntas. 
- No tengas miedo de hacer errores; lo que importa es la comunicación. 
- Pide ayuda cuando estés confundid@ o perdid@. 
- Ven a clase con la tarea preparada. 
- No asumas nada, pídele a la profesora que confirme las expectativas. 
- Participa activamente en clase; procura hablar por lo menos 10 minutos en cada clase. 
- Lee mucho en español. La lectura es muy buena para desarrollar la producción oral. 
- Escucha la radio en español. 
- Escucha música en español. 
- Ve a todas las películas de la escuela española. 
- Participa en muchas actividades co-curriculares. 
- Habla con otros profesores y con estudiantes de todos los niveles.
- ¡Diviértete!

