
## Lunes, 13 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

- Funciones: Narrar en el presente, describir situaciones
	- 3.1.1 Vocabulario en contexto: Las diversiones
- Preparación actividad e-Portafolio - Mi plato preferido (1:30)

### Detalles

- actividad de precalentamiento
- Pronunciación
- El verbo tener
- Mi plato preferido
	- pautas para la presentación
	- tiempo para practicar (escoger comida, lluvia de ideas sobre el vocabulario necesariop)

### Tarea

- practicar/preparar presentación 2

### Comentarios

- no me dio tiempo hacer lo del verbo tener (para el martes)







## Martes, 14 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

- Funciones: Narrar en el presente, describir situaciones
- 3.4.1 Gramática en contexto: Present tense of ir and ir a + infinitive
- Estrategias para la comprensión auditiva
- Preparación actividad e-Portafolio - Mi plato preferido (1:30)


### Detalles

- Más gustar
- El verbo tener
- Ir e ir a + inf. 
- ensayar presentación

### Tarea

- bien
- hicimos todo

### Comentarios

- mucha gramática al final, pero bien





## Miércoles, 15 de julio

### Reunión de nivel

- horario la semana que viene
- mesa redonda
- madison lucero







## Jueves, 16 de julio

### Plan

Capítulo 3 ¿Qué hacen para divertirse?

Funciones: Narrar en el presente, describir situaciones

Presentación 
Mi plato preferido (1:30 minutos) Grabar en ZOOM

3.4.3 Gramática en contexto: Present tense of hacer, poner, salir, traer and oír

3.4.4 Gramática en contexto: Numbers 100 to 2,000,000

### Detalles

- presentaciones
- verbos -go
- hablar de números

### Tarea


### Comentarios







## Viernes, 17 de julio

### Plan

Capítulo 4 ¿Cómo es tu familia?

Funciones: Narrar en el presente, describir situaciones
 
Instrucciones Examen Oral 1

4.1.1 Vocabulario en contexto: Los miembros de la familia


### Detalles

- Grabaciones
	- P1seccionC!, P2seccionC!
	- P1seccionB!, P2seccionB!
- repasar verbos go (resaltar semejanzas con decir, tener)
- los números (actividad de práctica)
- la familia (vocab y actividad)
- hablar de examen oral
	- qué hacemos?
	- cuándo? (horario el miércoles)

### Tarea

- NA

### Comentarios

- Apenas hablamos de la familia
